// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import ()

type SegToUser struct {
	UserID int32 `json:"user_id"`
	SegID  int32 `json:"seg_id"`
}

type Segment struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID int32 `json:"id"`
}
